version: '3'
services:
  php_composer:
    image: unnamed22090/php_composer:latest
    build:
      dockerfile: Dockerfile
      context: .
      args:
        time_zone: ${TimeZone}
    env_file:
      - .env
